/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AKlamTerm extends PTerm
{
    private PKlam _klam_;

    public AKlamTerm()
    {
        // Constructor
    }

    public AKlamTerm(
        @SuppressWarnings("hiding") PKlam _klam_)
    {
        // Constructor
        setKlam(_klam_);

    }

    @Override
    public Object clone()
    {
        return new AKlamTerm(
            cloneNode(this._klam_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKlamTerm(this);
    }

    public PKlam getKlam()
    {
        return this._klam_;
    }

    public void setKlam(PKlam node)
    {
        if(this._klam_ != null)
        {
            this._klam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._klam_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._klam_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._klam_ == child)
        {
            this._klam_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._klam_ == oldChild)
        {
            setKlam((PKlam) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
